"use client";
import { Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { approveDraft, createDraft, editDraft, isApproved, type Draft, type Run } from "./workspace-model";

export function DraftContent({ draft, run, title, format, ending, editing, text, approved, stale, onChange, onNotice, onOpenBrief, onEditingChange, onTextChange }: { draft: Draft | null; run: Run; title: string; format: "whatsapp" | "script"; ending: string; editing: boolean; text: string; approved: boolean; stale: boolean; onChange: (run: Run) => void; onNotice: (message: string) => void; onOpenBrief: () => void; onEditingChange: (value: boolean) => void; onTextChange: (value: string) => void }) {
  if (!draft) { const ready = isApproved(run); return <div className="py-8"><h2 className="text-base font-medium">{ready ? "Turn this brief into a draft." : "Approve your research first."}</h2><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">{ready ? `Uses approved research v${run.version} and the sample template.` : "Review the brief before creating content."}</p><Button className="mt-5" onClick={() => ready ? (onChange(createDraft({ run, title, format, ending })), onNotice("Draft created.")) : onOpenBrief()}>{ready ? "Create draft" : "Review research"}</Button></div>; }
  return <><div className="flex items-center justify-between border-b border-border pb-3"><p className="text-xs text-muted-foreground">Draft v{draft.version} · Research v{draft.researchVersion}{approved ? " · Approved" : ""}</p><Button variant="ghost" disabled={editing} onClick={() => { onTextChange(draft.text); onEditingChange(true); }}>Edit</Button></div>{stale ? <div className="mt-5 border-s-2 border-foreground ps-4"><p className="text-sm font-medium">Research updated</p><p className="mt-2 text-[13px] text-muted-foreground">Approve the new brief to replace this draft.</p><Button className="mt-3" variant="outline" disabled={!isApproved(run) || editing} onClick={() => { onChange(createDraft({ run, title, format, ending })); onNotice("Draft updated. Review the new wording."); }}>Replace with updated brief</Button></div> : null}{editing ? <div className="mt-6"><Textarea id="draft-text" className="min-h-[400px] leading-7" value={text} onChange={(event) => onTextChange(event.target.value)} /><div className="mt-4 flex gap-2"><Button disabled={!text.trim()} onClick={() => { onChange({ ...run, drafts: { ...run.drafts, [format]: editDraft(draft, text) } }); onEditingChange(false); onNotice("Draft saved."); }}>Save draft</Button><Button variant="ghost" onClick={() => onEditingChange(false)}>Cancel</Button></div></div> : <div className="space-y-5 py-7">{draft.text.split("\n\n").map((block, index) => <p key={index} className={`whitespace-pre-wrap break-words text-[15px] leading-7 ${index === 0 ? "font-semibold" : ""}`}>{index === 0 && format === "whatsapp" ? block.replace(/^\*|\*$/g, "") : block}</p>)}</div>}<div className="mt-5 flex items-center justify-between border-t border-border pt-5"><Button variant="ghost" disabled={editing} onClick={async () => { try { await navigator.clipboard.writeText(draft.text); onNotice("Draft copied."); } catch { onNotice("Clipboard unavailable. Select and copy the draft text."); } }}><Copy aria-hidden="true" />Copy draft</Button><Button disabled={approved || stale || !isApproved(run) || editing} onClick={() => { onChange({ ...run, drafts: { ...run.drafts, [format]: approveDraft(run, draft) } }); onNotice(`Draft v${draft.version} approved.`); }}>{approved ? "Approved" : "Approve draft"}</Button></div></>;
}
