"use client";

import type { RefObject } from "react";
import { ArrowRight, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { DraftPanel } from "./workspace-draft";
import { approveRun, canApprove, correctClaim, isApproved, reviseRun, type Claim, type Run, type Topic } from "./workspace-model";
import { EmptyResearch } from "./topic-detail-empty";

export function TopicDetailBody({ topic, run, claim, tab, outline, summary, editing, disputed, evidenceRef, onOutlineChange, onSummaryChange, onEditingChange, onClaimChange, onTabChange, onChange, onNotice, onUpdateRun, onStart }: {
  topic: Topic; run: Run | undefined; claim: Claim | undefined; tab: "brief" | "drafts"; outline: string; summary: string; editing: boolean; disputed: Claim[]; evidenceRef: RefObject<HTMLElement | null>;
  onOutlineChange: (value: string) => void; onSummaryChange: (value: string) => void; onEditingChange: (value: boolean) => void; onClaimChange: (value: string | null) => void; onTabChange: (value: "brief" | "drafts") => void; onChange: (topic: Topic) => void; onNotice: (message: string) => void; onUpdateRun: (run: Run) => void; onStart: () => void;
}) {
  if (tab === "drafts") return run ? <DraftPanel key={run.id} run={run} title={topic.title} onChange={onUpdateRun} onNotice={onNotice} onOpenBrief={() => onTabChange("brief")} /> : <EmptyResearch onStart={onStart} />;
  return <>
    <details className="border-b border-border py-4" open={!run}><summary className="w-fit cursor-pointer rounded-sm text-[13px] text-muted-foreground">Research outline</summary><div className="max-w-xl pb-2 pt-4"><label htmlFor="outline" className="mb-2 block text-xs text-muted-foreground">One subquestion per line</label><Textarea id="outline" rows={4} value={outline} onChange={(event) => onOutlineChange(event.target.value)} /><Button variant="outline" className="mt-3" disabled={outline === topic.outline} onClick={() => { onChange({ ...topic, outline }); onNotice("Outline saved."); }}>Save outline</Button></div></details>
    <div className={`grid items-start gap-8 pt-8 ${claim ? "xl:grid-cols-[minmax(0,1fr)_280px]" : ""}`}><div className="min-w-0 max-w-[720px]">{run ? <Brief run={run} claim={claim} summary={summary} editing={editing} disputed={disputed} onSummaryChange={onSummaryChange} onEditingChange={onEditingChange} onClaimChange={onClaimChange} onTabChange={onTabChange} onUpdateRun={onUpdateRun} onNotice={onNotice} /> : <EmptyResearch onStart={onStart} />}</div>{claim ? <Evidence claim={claim} run={run} evidenceRef={evidenceRef} onClose={() => onClaimChange(null)} onCorrect={onUpdateRun} onNotice={onNotice} /> : null}</div>
  </>;
}

function Brief({ run, claim, summary, editing, disputed, onSummaryChange, onEditingChange, onClaimChange, onTabChange, onUpdateRun, onNotice }: { run: Run; claim: Claim | undefined; summary: string; editing: boolean; disputed: Claim[]; onSummaryChange: (value: string) => void; onEditingChange: (value: boolean) => void; onClaimChange: (value: string | null) => void; onTabChange: (value: "brief" | "drafts") => void; onUpdateRun: (run: Run) => void; onNotice: (message: string) => void }) {
  return <><div className="mb-5 flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">Overview</h2><div className="flex items-center gap-3"><span className="text-xs text-muted-foreground">v{run.version}{isApproved(run) ? " · Approved" : ""}</span><Button variant="ghost" disabled={editing} onClick={() => { onSummaryChange(run.summary); onEditingChange(true); }}>Edit</Button></div></div>{editing ? <div><Textarea id="brief-summary" className="min-h-44 leading-7" value={summary} onChange={(event) => onSummaryChange(event.target.value)} /><p className="mt-3 text-xs text-muted-foreground">Changes create a new version for approval.</p><div className="mt-4 flex gap-2"><Button disabled={!summary.trim()} onClick={() => { if (summary !== run.summary) onUpdateRun(reviseRun(run, { summary, claims: run.claims })); onEditingChange(false); onNotice("Brief saved for review."); }}>Save brief</Button><Button variant="ghost" onClick={() => onEditingChange(false)}>Cancel</Button></div></div> : <p className="whitespace-pre-wrap text-[15px] leading-7">{run.summary || "Edit this brief to add your findings."}</p>}<div className="mb-2 mt-9 flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">Findings</h2>{disputed.length ? <button onClick={() => onClaimChange(disputed[0].id)} className="text-xs underline">{disputed.length} claim needs review</button> : null}</div>{run.claims.map((item, index) => <button key={item.id} aria-pressed={claim?.id === item.id} onClick={() => onClaimChange(claim?.id === item.id ? null : item.id)} className={`grid w-full grid-cols-[20px_minmax(0,1fr)_14px] gap-3 border-b border-border px-2 py-5 text-start ${claim?.id === item.id ? "bg-secondary" : "hover:bg-surface-subtle"}`}><span className="text-xs text-muted-foreground">{index + 1}</span><span className="text-sm leading-6">{item.text}{item.review.kind === "disputed" ? <span className="mt-2 block text-xs text-muted-foreground">Review wording</span> : null}</span><ArrowRight className="size-3.5" aria-hidden="true" /></button>)}{!run.claims.length ? <p className="py-4 text-[13px] text-muted-foreground">No evidence attached. This brief has not been fact-checked.</p> : null}<div className="mt-8 flex items-center justify-between gap-4"><p className="text-xs text-muted-foreground">{isApproved(run) ? "Ready to draft." : disputed.length ? "Resolve the flagged claim before approval." : "Approve this version after reviewing the evidence."}</p>{isApproved(run) ? <Button onClick={() => onTabChange("drafts")}>Prepare a draft <ArrowRight aria-hidden="true" /></Button> : <Button disabled={!canApprove(run) || editing} onClick={() => { onUpdateRun(approveRun(run)); onNotice(`Research v${run.version} approved.`); }}>Approve brief</Button>}</div></>;
}

function Evidence({ claim, run, evidenceRef, onClose, onCorrect, onNotice }: { claim: Claim; run: Run | undefined; evidenceRef: RefObject<HTMLElement | null>; onClose: () => void; onCorrect: (run: Run) => void; onNotice: (message: string) => void }) {
  return <aside ref={evidenceRef} tabIndex={-1} aria-label="Evidence and review" className="border-t border-border pt-5 xl:border-s xl:border-t-0 xl:ps-6"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Evidence</h2><Button size="icon-sm" variant="ghost" aria-label="Close evidence" onClick={onClose}><X aria-hidden="true" /></Button></div><p className="mt-4 text-xs text-muted-foreground">{claim.source}</p><blockquote className="mt-4 text-sm leading-7">“{claim.excerpt}”</blockquote><h3 className="mt-6 text-xs font-semibold">Review</h3><p className="mt-2 text-[13px] text-muted-foreground">{claim.review.note}</p>{claim.review.kind === "disputed" ? <><h3 className="mt-6 text-xs font-semibold">Suggested wording</h3><p className="mt-2 text-sm leading-7">{claim.review.correction}</p><Button className="mt-5" variant="outline" onClick={() => { if (run) { onCorrect(correctClaim(run, claim.id)); onNotice("Claim corrected. Review the updated brief."); } }}>Use qualified wording</Button></> : <p className="mt-5 text-xs text-muted-foreground">Wording matches the excerpt.</p>}</aside>;
}
